[tools]
"java" = { version = "openjdk" } # This is for openapi-generator-cli, which requires Java to run.
"npm:@openapitools/openapi-generator-cli" = { version = "latest", npm_args = "--ignore-scripts=false"}
