import { expect, test } from '@playwright/test';

test('draft terms only run on search, with JSON conditions and matching cursors', async ({ page }) => {
  const requests: URL[] = [];
  await page.route('**/api/v0/contents?*', (route) => {
    const url = new URL(route.request().url());
    requests.push(url);
    return route.fulfill({ json: { items: url.searchParams.has('condition') ? [{ id: '10000000-0000-4000-8000-000000000001', mediaType: 'image/avif', contentUrl: '/test.avif', thumbnailUrl: '/test.avif', tags: [], invalidTags: [] }] : [], ...(url.searchParams.has('condition') && !url.searchParams.has('cursor') ? { nextCursor: 'opaque+/=日本語' } : {}) } });
  });
  await page.route('**/test.avif', (route) => route.fulfill({ path: '../sample/00065786-f916-4e2c-85bc-3db5e4c0cb71.avif', contentType: 'image/avif' }));
  await page.goto('/');
  await expect(page.getByRole('heading', { name: '検索', exact: true })).toHaveCount(0);
  await expect(page.getByLabel('条件の種類')).toHaveCount(0);
  await expect(page.getByRole('button', { name: '条件をクリア', exact: true }).locator('svg')).toHaveClass(/lucide-trash-2/);
  await expect(page.getByRole('button', { name: '検索', exact: true })).toHaveClass(/btn-circle.*btn-outline.*btn-primary/);
  await expect(page.getByRole('button', { name: '条件をクリア', exact: true })).toHaveClass(/btn-circle.*btn-outline.*btn-secondary/);
  await expect(page.getByLabel('タグ名', { exact: true }).locator('..').locator('svg')).toHaveClass(/lucide-hash/);
  await expect(page.getByLabel('タグ名', { exact: true }).locator('..').getByText('タグ名')).toHaveCount(0);
  await page.getByLabel('タグ名', { exact: true }).fill('category');
  await page.getByRole('button', { name: '値を追加', exact: true }).click();
  await expect(page.getByLabel('値 1', { exact: true }).locator('..').locator('svg')).toHaveClass(/lucide-tag/);
  await page.getByLabel('値 1', { exact: true }).fill('日本語,+&');
  await page.getByRole('button', { name: '値を追加', exact: true }).click();
  await expect(page.getByRole('button', { name: '条件に追加', exact: true })).toHaveClass(/rounded-full/);
  await expect(page.getByRole('button', { name: '条件に追加', exact: true })).toHaveClass(/btn-outline/);
  await expect(page.getByRole('button', { name: '条件に追加', exact: true })).toHaveClass(/btn-success/);
  await expect(page.getByRole('button', { name: '条件に追加', exact: true }).locator('svg')).toHaveClass(/lucide-check/);
  await page.getByRole('button', { name: '条件に追加', exact: true }).click();
  await expect(page.getByRole('alert')).toHaveText('空の値は追加できません。');
  await page.getByRole('button', { name: '値 2 を削除', exact: true }).click();
  await page.getByRole('button', { name: '条件に追加', exact: true }).click();
  await expect(page.getByLabel('category: 日本語,+&')).toBeVisible();
  const editCategory = page.getByRole('button', { name: '条件 1 を編集', exact: true });
  await editCategory.focus();
  await editCategory.click();
  await expect(page.getByLabel('タグ名', { exact: true })).toHaveValue('category');
  await expect(page.getByLabel('値 1', { exact: true })).toHaveValue('日本語,+&');
  await page.getByRole('button', { name: '条件に追加', exact: true }).click();
  await expect(page.getByLabel('category: 日本語,+&')).toBeVisible();
  await page.getByLabel('タグ名', { exact: true }).fill('authors');
  await page.getByRole('button', { name: '条件に追加', exact: true }).click();
  await expect(page.getByLabel('authors', { exact: true })).toBeVisible();
  const editAuthors = page.getByRole('button', { name: '条件 2 を編集', exact: true });
  await editAuthors.focus();
  await editAuthors.click();
  await expect(page.getByLabel('authors', { exact: true })).toHaveCount(0);
  await expect(page.getByLabel('タグ名', { exact: true })).toHaveValue('authors');
  await page.getByRole('button', { name: '条件に追加', exact: true }).click();
  await expect(page.getByLabel('authors', { exact: true })).toBeVisible();
  await expect(page.getByRole('checkbox', { name: 'image/avif' })).toBeChecked();
  await expect(page.getByRole('checkbox', { name: 'image/avif' })).toBeDisabled();
  const avifControl = page.getByRole('checkbox', { name: 'image/avif' }).locator('..');
  await expect(avifControl).toHaveClass(/btn-soft/);
  expect(requests).toHaveLength(0);
  await page.screenshot({ path: `test-results/search-${test.info().project.name}.png`, fullPage: true });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.getByRole('button', { name: '検索', exact: true }).click();
  await expect(page).toHaveURL(/#\/contents$/);
  await page.getByRole('link', { name: '画像 1 を開く', exact: true }).scrollIntoViewIfNeeded();
  await expect.poll(() => requests.length).toBe(2);
  const condition = [
    { kind: 'tagMatch', key: 'category', values: ['日本語,+&'] },
    { kind: 'tagExists', key: 'authors' },
  ];
  for (const request of requests) expect(JSON.parse(request.searchParams.get('condition')!)).toEqual(condition);
  expect(requests[0].searchParams.get('cursor')).toBeNull();
  expect(requests[1].searchParams.get('cursor')).toBe('opaque+/=日本語');
  const removeAuthors = page.getByRole('button', { name: '条件 2 を削除', exact: true });
  const termActions = removeAuthors.locator('..');
  await expect(termActions).toHaveCSS('opacity', '0');
  if (test.info().project.name === 'mobile') await removeAuthors.focus();
  else await page.getByRole('listitem').filter({ has: page.getByLabel('authors', { exact: true }) }).hover();
  await expect(termActions).toHaveCSS('opacity', '1');
  await expect(page.getByRole('button', { name: '条件 2 を編集', exact: true })).toHaveClass(/btn btn-square btn-xs rounded-full/);
  await expect(removeAuthors).toHaveClass(/btn btn-square btn-xs rounded-full/);
  const authorsBadge = page.getByLabel('authors', { exact: true });
  const termItem = page.getByRole('listitem').filter({ has: authorsBadge });
  const [badgeBox, actionsBox, itemBox] = await Promise.all([authorsBadge.boundingBox(), termActions.boundingBox(), termItem.boundingBox()]);
  expect(badgeBox!.x + badgeBox!.width).toBeLessThanOrEqual(actionsBox!.x);
  expect(itemBox!.width).toBeCloseTo(badgeBox!.width, 0);
  await removeAuthors.click();
  expect(requests).toHaveLength(2);
  await page.getByRole('button', { name: '検索', exact: true }).click();
  await page.getByRole('link', { name: '画像 1 を開く', exact: true }).scrollIntoViewIfNeeded();
  await expect.poll(() => requests.length).toBe(4);
  expect(requests[2].searchParams.get('cursor')).toBeNull();
  expect(JSON.parse(requests[2].searchParams.get('condition')!)).toEqual([condition[0]]);
  await page.getByRole('button', { name: '条件をクリア', exact: true }).click();
  expect(requests).toHaveLength(4);
  await page.getByRole('button', { name: '検索', exact: true }).click();
  await expect.poll(() => requests.length).toBe(5);
  expect(requests[4].searchParams.has('condition')).toBe(false);
  expect(requests[4].searchParams.has('cursor')).toBe(false);
  await page.getByRole('button', { name: '検索', exact: true }).click();
  await expect.poll(() => requests.length).toBe(6);
});

test('term validation and normalization', async ({ page }) => {
  await page.goto('/');
  await page.getByLabel('タグ名', { exact: true }).fill('1bad');
  await page.getByRole('button', { name: '条件に追加', exact: true }).click();
  await expect(page.getByRole('alert')).toBeVisible();
  await page.getByLabel('タグ名', { exact: true }).fill('ｃategory');
  await page.getByRole('button', { name: '値を追加', exact: true }).click();
  await page.getByLabel('値 1', { exact: true }).fill('e\u0301');
  await page.getByRole('button', { name: '条件に追加', exact: true }).click();
  await expect(page.getByLabel('category: é', { exact: true })).toBeVisible();
  await page.getByLabel('タグ名', { exact: true }).fill('empty');
  await page.getByRole('button', { name: '値を追加', exact: true }).click();
  await page.getByRole('button', { name: '条件に追加', exact: true }).click();
  await expect(page.getByRole('alert')).toHaveText('空の値は追加できません。');
});
